# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassianlabs/docker-node-jdk-chrome-firefox

pipelines:
    default:
        - step:
              name: Install and test Client
              caches:
                  - node
              script:
                  - Xvfb :99 -ac -screen 0 1920x1080x24 &
                  - pushd client
                  - npm install
                  - npm run build
                  - npm run test -- --browsers ChromeHeadlessNoSandbox
                  - popd
              artifacts:
                  - ~/client/out
        - step:
              name: Install and test Server
              caches:
                  - node
              script:
                  - pushd server
                  - npm install
                  # TODO: Reenable once there are some tests
                  #                  - npm run test
                  - popd
              artifacts:
                  - ~/server/out
	- step:
	      name: Deploy Client
	      caches:
		  - node
	      deployment: test
	      script:
                  - npm install
		  - >
		    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
		      sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
		      apt-get update && \
		      apt-get install -y google-chrome-stable xvfb procps       
		  - npm run test:ci
		  #- npm run e2e:ci #TODO
		  - npm run build:prod
		  - pipe: atlassian/firebase-deploy:0.3.0
		    variables:
		      FIREBASE_TOKEN: '$FIREBASE_TOKEN_CI'
