# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassianlabs/docker-node-jdk-chrome-firefox

pipelines:
  default:
    - step:
        name: Install and test Client
        caches:
          - node
        script:
          - Xvfb :99 -ac -screen 0 1920x1080x24 &
          - pushd client
          - npm install
          - npm run lint
          - npm run build
          - npm run coverage -- --browsers ChromeHeadlessNoSandbox
          - popd
        artifacts:
          - ~/client/out
    - step:
        name: Install and test Server
        caches:
          - node
        script:
          - pushd server
          - npm install
          - npm run lint
          - npm run coverage 
          - popd
        artifacts:
          - ~/server/out

